[project]
name = "openlibrary-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dlt[workspace]>=1.22.0",
    "marimo>=0.20.1",
]
